twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'form/my_theme.html.twig' ] # or ['bootstrap_5_layout.html.twig', 'form/my_theme.html.twig' ]
when@test:
    twig:
        strict_variables: true
